package com.interfaz;

//import com.codigo.AperturaCuentaUser;
import com.codigo.DepositosRetiros;

public class RealizarDeposito extends javax.swing.JFrame {

    public RealizarDeposito() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtDepoRealizado.setVisible(false);
        txtDataObli.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background1 = new javax.swing.JPanel();
        jLabelTittle = new javax.swing.JLabel();
        Background2 = new javax.swing.JPanel();
        jLabelNumeroCuenta = new javax.swing.JLabel();
        jTextNumCuenta = new javax.swing.JTextField();
        jLabelMontoDeposito = new javax.swing.JLabel();
        jTextDeposito = new javax.swing.JTextField();
        btnEfectuar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtDepoRealizado = new javax.swing.JLabel();
        txtDataObli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelTittle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTittle.setText("REALIZAR DEPÓSITO");

        javax.swing.GroupLayout Background1Layout = new javax.swing.GroupLayout(Background1);
        Background1.setLayout(Background1Layout);
        Background1Layout.setHorizontalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background1Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabelTittle)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        Background1Layout.setVerticalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelTittle)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 130));

        Background2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNumeroCuenta.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabelNumeroCuenta.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumeroCuenta.setText("NÚMERO DE CUENTA");

        jLabelMontoDeposito.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMontoDeposito.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabelMontoDeposito.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMontoDeposito.setText("MONTO A DEPOSITAR");

        btnEfectuar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnEfectuar.setText("EFECTUAR");
        btnEfectuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectuarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtDepoRealizado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtDepoRealizado.setForeground(new java.awt.Color(51, 255, 51));
        txtDepoRealizado.setText("DEPÓSITO REALIZADO");

        txtDataObli.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtDataObli.setForeground(new java.awt.Color(255, 0, 51));
        txtDataObli.setText("DATOS OBLIGATORIOS");

        javax.swing.GroupLayout Background2Layout = new javax.swing.GroupLayout(Background2);
        Background2.setLayout(Background2Layout);
        Background2Layout.setHorizontalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background2Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background2Layout.createSequentialGroup()
                        .addGroup(Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMontoDeposito)
                            .addGroup(Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelNumeroCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextNumCuenta))
                            .addComponent(jTextDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background2Layout.createSequentialGroup()
                        .addComponent(btnEfectuar)
                        .addGap(354, 354, 354))))
            .addGroup(Background2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtDepoRealizado))
                    .addComponent(txtDataObli))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Background2Layout.setVerticalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelNumeroCuenta)
                .addGap(18, 18, 18)
                .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabelMontoDeposito)
                .addGap(18, 18, 18)
                .addComponent(jTextDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataObli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDepoRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEfectuar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 840, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal abrirMenuPrincipal = new MenuPrincipal();
        abrirMenuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEfectuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectuarActionPerformed

        String numCuenta = jTextNumCuenta.getText();
        String montoDepo = jTextDeposito.getText();

        if (numCuenta.isEmpty() || montoDepo.isEmpty()) {
            txtDataObli.setVisible(true);
        } else {
            Double montoDeposito = Double.parseDouble(montoDepo);
            DepositosRetiros depo = new DepositosRetiros(montoDeposito, numCuenta);
            depo.depositar();
            txtDepoRealizado.setVisible(true);
            jTextNumCuenta.setText("");
            jTextDeposito.setText("");
            txtDepoRealizado.setVisible(false);

        }
//        Double montoDeposito = Double.parseDouble(montoDepo);
//        DepositosRetiros depo = new DepositosRetiros( montoDeposito, numCuenta);
//        depo.depositar();
//        txtDepoRealizado.setVisible(true);
//        jTextNumCuenta.setText("");
//        jTextDeposito.setText("");
//        txtDepoRealizado.setVisible(false);

    }//GEN-LAST:event_btnEfectuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background1;
    private javax.swing.JPanel Background2;
    private javax.swing.JButton btnEfectuar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelMontoDeposito;
    private javax.swing.JLabel jLabelNumeroCuenta;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JTextField jTextDeposito;
    private javax.swing.JTextField jTextNumCuenta;
    private javax.swing.JLabel txtDataObli;
    private javax.swing.JLabel txtDepoRealizado;
    // End of variables declaration//GEN-END:variables
}
